server:
  addr: :5001
  certificate: /config/certs/cert.pem
  key: /config/certs/key.pem
token:
  issuer: "Aurea auth server"
  expiration: 900

users:
  "": {}

ldap_auth:
  # Addr is the hostname:port or ip:port
  addr: devfactory.local:389
  # Setup tls connection method to be
  # "" or "none": the communication won't be encrypted
  # "always": setup LDAP over SSL/TLS
  # "starttls": sets StartTLS as the encryption method
  tls: none
  # In case bind DN and password is required for querying user information,
  # specify them here. Plain text password is read from the file.
  bind_dn: 'CN=Service Dregistry,CN=Users,DC=devfactory,DC=local'
  bind_password_file: /config/auth_passwd
  # User query settings. ${account} is expanded from auth request 
  base: DC=devfactory,DC=local
  filter: (&(sAMAccountName=${account})(objectClass=*))
acl:
  # This will allow authenticated users to pull/push
  - match: {account: "", type: "registry", name: "catalog"}
    actions: ["*"]
  - match: {account: "/.+/"}
    actions: ["*"]
  - match: {account: ""}
    actions: ["*"]
